language: swift
osx_image: xcode10
script:
  - swift package generate-xcodeproj
  - xcodebuild -scheme SwiftRegexExtractor -sdk macosx10.14 -destination arch=x86_64 build test -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash) -J SwiftRegexExtractor
