language: swift
osx_image: xcode10
script:
  - swift build -c release
  - swift package generate-xcodeproj
  - xcodebuild -scheme SwiftRegexExtractor -sdk macosx -destination arch=x86_64 test -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
